server:
  port: 8082
spring:
  security:
    oauth2:
      client:
        registration:
          custom-client:
            client-id: pts2.elinext.com
            client-secret: super_secret
            client-name: pts2.elinext.com
            scope: openid, email, profile
            provider: elinext-is
            redirect-uri-template: http://localhost:8082/login/oauth2/code/
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          elinext-is:
            authorization-uri: https://auth.elinext.com/connect/authorize
            token-uri: https://auth.elinext.com/connect/token
            user-info-uri: https://auth.elinext.com/connect/userinfo
            jwk-set-uri: https://auth.elinext.com/.well-known/openid-configuration/jwks
            user-name-attribute: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
logging:
  level:
    root: info
    org.springframework.web: info

logout-success-uri: https://auth.elinext.com/Account/Logout
end-session-endpoint: https://auth.elinext.com/connect/endsession
      # security:
      #  oauth2:
      #   client:
      #    registration:
      #     custom-client:
      #      client-id: 0oanfi59ym2seU7N2356
      #     client-secret: y5sNVdLHr61ELaKIZGVS_EEagaYgySUKTkZb49mU
      #    client-name: PTS2
      #   scope: openid profile email
      #  provider: okta
      # redirect-uri-template: http://localhost:8082/login/oauth2/code/
      #client-authentication-method: basic
      #authorization-grant-type: authorization_code

      #provider:
      # okta:
      #  authorization-uri: https://dev-229121.okta.com/oauth2/default/v1/authorize
      # token-uri: https://dev-229121.okta.com/oauth2/default/v1/token
      #user-info-uri: https://dev-229121.okta.com/oauth2/default/v1/userinfo
      #jwk-set-uri: https://dev-229121.okta.com/oauth2/default/v1/keys
    #user-name-attribute: sub
